// Code generated by Kitex v0.10.3. DO NOT EDIT.

package jobservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	job "kitex/kitex_gen/path/to/your/package/job"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateJob(ctx context.Context, Req *job.Job, callOptions ...callopt.Option) (r *job.CreateJobResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kJobServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kJobServiceClient struct {
	*kClient
}

func (p *kJobServiceClient) CreateJob(ctx context.Context, Req *job.Job, callOptions ...callopt.Option) (r *job.CreateJobResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateJob(ctx, Req)
}
