// Code generated by Kitex v0.10.3. DO NOT EDIT.

package jobservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
	job "kitex/kitex_gen/path/to/your/package/job"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateJob": kitex.NewMethodInfo(
		createJobHandler,
		newCreateJobArgs,
		newCreateJobResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	jobServiceServiceInfo                = NewServiceInfo()
	jobServiceServiceInfoForClient       = NewServiceInfoForClient()
	jobServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return jobServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return jobServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return jobServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "JobService"
	handlerType := (*job.JobService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.10.3",
		Extra:           extra,
	}
	return svcInfo
}

func createJobHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(job.Job)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(job.JobService).CreateJob(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateJobArgs:
		success, err := handler.(job.JobService).CreateJob(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateJobResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateJobArgs() interface{} {
	return &CreateJobArgs{}
}

func newCreateJobResult() interface{} {
	return &CreateJobResult{}
}

type CreateJobArgs struct {
	Req *job.Job
}

func (p *CreateJobArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(job.Job)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *CreateJobArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *CreateJobArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *CreateJobArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateJobArgs) Unmarshal(in []byte) error {
	msg := new(job.Job)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateJobArgs_Req_DEFAULT *job.Job

func (p *CreateJobArgs) GetReq() *job.Job {
	if !p.IsSetReq() {
		return CreateJobArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateJobArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateJobArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateJobResult struct {
	Success *job.CreateJobResp
}

var CreateJobResult_Success_DEFAULT *job.CreateJobResp

func (p *CreateJobResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(job.CreateJobResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *CreateJobResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *CreateJobResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *CreateJobResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateJobResult) Unmarshal(in []byte) error {
	msg := new(job.CreateJobResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateJobResult) GetSuccess() *job.CreateJobResp {
	if !p.IsSetSuccess() {
		return CreateJobResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateJobResult) SetSuccess(x interface{}) {
	p.Success = x.(*job.CreateJobResp)
}

func (p *CreateJobResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateJobResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateJob(ctx context.Context, Req *job.Job) (r *job.CreateJobResp, err error) {
	var _args CreateJobArgs
	_args.Req = Req
	var _result CreateJobResult
	if err = p.c.Call(ctx, "CreateJob", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
